name: Upload to Hackage
description: Upload an sdist archive to hackage.haskell.org

inputs:
  archive:
    description: The sdist archive to upload
    required: true
  token:
    description: The Hackage auth token
    required: true
  candidate:
    description: Whether to upload the package as a candidate
    default: true
  url:
    description: Hackage URL
    default: https://hackage.haskell.org

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          // https://github.com/actions/toolkit/issues/1124#issuecomment-1305836110
          const inputs = ${{ toJSON(inputs) }}

          const script = require('${{ github.action_path }}/upload-hackage.js')
          await script({ inputs, core, glob, exec })
