name: hackage-upload
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

defaults:
  run:
    working-directory: hackage-upload/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          version: 22.10.0
          src: hackage-upload/

      - name: Install deps
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Configure pyright
        run: |
          cat > pyrightconfig.json <<EOF
          {
            "strict": ["*"],
            "reportUnknownMemberType": false,
            "venvPath": ".",
            "venv": "venv"
          }
          EOF

      - uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.278
          working-directory: hackage-upload/
