name: 'Setup Haskell'
description: 'Set up a specific version of GHC and Cabal and add the command-line tools to the PATH'
author: 'GitHub'
inputs:
  ghc-version:
    required: false
    description: 'Version of GHC to use. If set to "latest", it will always get the latest stable version. If set to "head", it will always get the latest build of GHC.'
    default: 'latest'
  cabal-version:
    required: false
    description: 'Version of Cabal to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  stack-version:
    required: false
    description: 'Version of Stack to use. If set to "latest", it will always get the latest stable version.'
    default: 'latest'
  enable-stack:
    required: false
    description: 'If specified, will setup Stack.'
  stack-no-global:
    required: false
    description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally.'
  stack-setup-ghc:
    required: false
    description: 'If specified, enable-stack must be set. Will run stack setup to install the specified GHC.'
  cabal-update:
    required: false
    default: true
    description: 'Set to false to prevent `cabal update` from being run.'
  disable-matcher:
    required: false
    description: 'If specified, disables match messages from GHC as GitHub CI annotations.'
outputs:
  ghc-path:
    description: 'The path of the ghc executable _directory_'
  cabal-path:
    description: 'The path of the cabal executable _directory_'
  stack-path:
    description: 'The path of the stack executable _directory_'
  cabal-store:
    description: 'The path to the cabal store'
  stack-root:
    description: 'The path to the stack root (equal to the STACK_ROOT environment variable if it is set; otherwise an OS-specific default)'
  ghc-exe:
    description: 'The path of the ghc _executable_'
  cabal-exe:
    description: 'The path of the cabal _executable_'
  stack-exe:
    description: 'The path of the stack _executable_'
runs:
  using: 'node16'
  main: 'dist/index.js'
