name: Check dist

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-dist:
    strategy:
      matrix:
        action: ['setup', 'hlint-setup', 'hlint-run']
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.action }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Rebuild the dist/ directory
        run: npm run build

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/* | wc -l)" -gt "0" ]; then
            echo "::error::Detected uncommitted changes after build. Please run \`npm run build\` locally and commit the changes. See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js or post.js are different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
