name: /hlint-run
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

defaults:
  run:
    working-directory: 'hlint-run'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: hlint-run/package-lock.json
    - run: npm install
    - run: npm run all

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up HLint
      uses: ./hlint-setup

    - run: hlint --version

    - uses: ./hlint-run
      with:
        path: ./hlint-run/test/Example.hs
