name: "/hlint-run"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

defaults:
  run:
    working-directory: "hlint-run"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"
        cache-dependency-path: hlint-run/yarn.lock
    - run: yarn
    - run: yarn compile
    - run: yarn package
    - run: yarn test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up HLint
      uses: ./hlint-setup

    - run: hlint --version

    - uses: ./hlint-run
      with:
        path: ./hlint-run/test/Example.hs
